array
(
   "01_Inscribe" => array
   (
      "AccessMethod" => "Friend_Inscribed_Not",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscribe",
      "Name" => "Inscrever-me",
      "Name_ES" => "Inscribir-me",
      "Name_UK" => "Inscribe",
      "Person" => "0",
      "Public" => "1",
   ),
   "01_Inscription" => array
   (
      "AccessMethod" => "Friend_Inscribed_Is",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription",
      "Anchor" => "Inscription",
      "Name" => "Inscrição",
      "Name_ES" => "Inscricion",
      "Name_UK" => "Inscription",
      "Person" => "0",
      "Public" => "1",
    ),
   "02_Certificates" => array
   (
      "AccessMethod" => "Friend_Certificates_Should",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription&Type=Certificates",
      "Anchor" => "Certificates",
      "Name" => "Certificados",
      "Name_ES" => "Certificados",
      "Name_UK" => "Certificates",
      "Person" => "0",
      "Public" => "1",
    ),
   "03_Submissions" => array
   (
      "AccessMethod" => "Friend_Submissions_Should",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription&Type=Submissions",
      "Anchor" => "Submissions",
      "Name" => "Submissões",
      "Name_ES" => "Submissiones",
      "Name_UK" => "Submissions",
      "Person" => "0",
      "Public" => "1",
    ),
   "04_Speaker" => array
   (
      "AccessMethod" => "Friend_Speakers_Has",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Anchor" => "Speaker",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription&Type=Speaker",
      "Name" => "Dados do Palestrante",
      "Name_ES" => "Dados do Palestrante",
      "Name_UK" => "Speakers Data",
      "Person" => "0",
      "Public" => "1",
    ),
   "05_Assessors" => array
   (
      "AccessMethod" => "Friend_Assessors_Should",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Anchor" => "Assessors",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription&Type=Assessments",
      "Name" => "Avaliações",
      "Name_ES" => "Avaliaciones",
      "Name_UK" => "Assessments",
      "Person" => "0",
      "Public" => "1",
    ),
   "06_Collaborators" => array
   (
      "AccessMethod" => "Friend_Collaborators_Should",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription&Type=Collaborations",
      "Anchor" => "Collaborations",
      "Name" => "Colaborações",
      "Name_ES" => "Colaboraciones",
      "Name_UK" => "Collaborations",
      "Person" => "0",
      "Public" => "1",
    ),
   "07_Caravan" => array
   (
      "AccessMethod" => "Friend_Caravans_Should",
      "Admin" => "1",
      "Coordinator" => "1",
      "Friend" => "1",
      "Href" => "?Unit=".$this->Unit("ID")."&Event=".$this->Event("ID")."&ModuleName=Inscriptions&Action=Inscription&Type=Caravans",
      "Anchor" => "Caravan",
      "Name" => "Caravanas",
      "Name_ES" => "Caravanas",
      "Name_UK" => "Caravans",
      "Person" => "0",
      "Public" => "1",
    ),

);

